#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tempora']

package_data = \
{'': ['*']}

install_requires = \
['python-dateutil',
 'jaraco.collections',
 'jaraco.context',
 'jaraco.functools',
 'typing_extensions']

extras_require = \
{':extra == "test"': ['pytest-freezer', 'types-python-dateutil'],
 ':extra=="test"': ['freezegun', 'pytest'],
 ':platform_system == "Windows" and extra == "test"': ['tzdata'],
 ':python_version < "3.9" and extra == "test"': ['backports.zoneinfo']}

entry_points = \
{'console_scripts': ['calc-prorate = tempora:calculate_prorated_values']}

setup(name='tempora',
      version='5.12.0',
      description='',
      author=None,
      author_email='"Jason R. Coombs" <jaraco@jaraco.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>= 3.10',
     )
